# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectiontypes', '0017_auto_20161220_1636'),
        ('devices', '0002_device_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.BooleanField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.Connection')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterName', models.CharField(max_length=100)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection')),
                ('connectionPartner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.ConnectionPartner')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterBoolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterValue', models.BooleanField()),
                ('Parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connections.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterValue', models.IntegerField()),
                ('Parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connections.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterValue', models.GenericIPAddressField()),
                ('Parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connections.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterText100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterValue', models.CharField(max_length=100)),
                ('Parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connections.Parameter')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='devices',
            field=models.ManyToManyField(through='connections.ConnectionPartner', to='devices.Device'),
        ),
        migrations.AddField(
            model_name='connection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectiontypes.ConnectionType'),
        ),
    ]
