# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='connectionPartner',
        ),
        migrations.RemoveField(
            model_name='parameterboolean',
            name='Parameter',
        ),
        migrations.RemoveField(
            model_name='parameterint',
            name='Parameter',
        ),
        migrations.RemoveField(
            model_name='parameterip',
            name='Parameter',
        ),
        migrations.RemoveField(
            model_name='parametertext100',
            name='Parameter',
        ),
        migrations.AddField(
            model_name='parameterboolean',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection'),
        ),
        migrations.AddField(
            model_name='parameterboolean',
            name='connectionPartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.ConnectionPartner'),
        ),
        migrations.AddField(
            model_name='parameterboolean',
            name='parameterName',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameterint',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection'),
        ),
        migrations.AddField(
            model_name='parameterint',
            name='connectionPartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.ConnectionPartner'),
        ),
        migrations.AddField(
            model_name='parameterint',
            name='parameterName',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameterip',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection'),
        ),
        migrations.AddField(
            model_name='parameterip',
            name='connectionPartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.ConnectionPartner'),
        ),
        migrations.AddField(
            model_name='parameterip',
            name='parameterName',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametertext100',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection'),
        ),
        migrations.AddField(
            model_name='parametertext100',
            name='connectionPartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.ConnectionPartner'),
        ),
        migrations.AddField(
            model_name='parametertext100',
            name='parameterName',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
