# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_auto_20170114_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterboolean',
            old_name='parameterName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parameterboolean',
            old_name='parameterValue',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='parameterint',
            old_name='parameterName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parameterint',
            old_name='parameterValue',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='parameterip',
            old_name='parameterName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parameterip',
            old_name='parameterValue',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='parametertext100',
            old_name='parameterName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parametertext100',
            old_name='parameterValue',
            new_name='value',
        ),
    ]
