# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20170114_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='externalID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
