# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_configfile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='application',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
