# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_externalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='externalID',
        ),
    ]
