# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_externalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='externalID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
