# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_externalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHasDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childDevice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='childDevice', to='devices.Device')),
                ('parentDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentDevice', to='devices.Device')),
            ],
        ),
    ]
