# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20170330_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NonSensorDeviceHasInterfaces',
            new_name='NonSensorDeviceHasInterface',
        ),
    ]
