# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20170330_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NonSensorDeviceHasInterface',
            new_name='NonSensorDeviceHasInterfaces',
        ),
    ]
