# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-17 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20170330_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lastPing_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='lastPing_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
