# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
