# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20161123_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='datasheet',
            field=models.FileField(default=1, upload_to='uploads/datasheets'),
            preserve_default=False,
        ),
    ]
