# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import sensors.models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensortype_datasheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='datasheet',
            field=models.FileField(upload_to=sensors.models.user_directory_path),
        ),
    ]
