# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20161125_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
