# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import sensors.models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='datasheet',
            field=models.FileField(blank=True, upload_to=sensors.models.user_directory_path),
        ),
    ]
