# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0017_auto_20161220_1636'),
        ('sensors', '0006_auto_20161201_1024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensortypehasinterfaces',
            unique_together=set([('sensorType', 'connectionType')]),
        ),
    ]
