# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20170113_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalquantity',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
