# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_auto_20170119_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='externalID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
