# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_sensor_externalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='externalID',
        ),
    ]
