# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_remove_sensor_externalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorMeasures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, max_length=100)),
                ('outputFormat', models.CharField(blank=True, max_length=100)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Measurement')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor')),
            ],
        ),
    ]
