# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_sensormeasures'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortypecanmeasure',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensortypecanmeasure',
            name='accuracyUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.Unit'),
        ),
    ]
