# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-16 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_auto_20170904_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensormeasures',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.SensortypeCanMeasure'),
        ),
    ]
