# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0002_connectionparameter_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionparameter',
            name='size',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
