# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0003_connectionparameter_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionparameter',
            name='format',
            field=models.CharField(choices=[('int', 'Integer'), ('txt', 'Text'), ('bin', 'Binary'), ('Bit', 'Bits'), ('Byte', 'Byte'), ('IP', 'IP Address')], default='txt', max_length=10),
        ),
    ]
