# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0004_auto_20161102_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionhasparameter',
            name='isRequired',
        ),
        migrations.AddField(
            model_name='connectionhasparameter',
            name='needsToBeSet',
            field=models.BooleanField(default=True),
        ),
    ]
