# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0005_auto_20161103_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhasparameter',
            name='needsToBeSet',
            field=models.BooleanField(default=False),
        ),
    ]
