# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0006_auto_20161103_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionhasparameter',
            old_name='needsToBeSet',
            new_name='needsToBePreset',
        ),
    ]
