# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0008_auto_20161103_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontype',
            name='topology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='connectiontypes.Topology'),
            preserve_default=False,
        ),
    ]
