# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0009_connectiontype_topology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topology',
            options={'verbose_name_plural': 'topologies'},
        ),
    ]
