# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0011_auto_20161123_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionparameter',
            name='size',
            field=models.IntegerField(default=False),
        ),
    ]
