# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0013_auto_20161220_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionparameter',
            name='size',
            field=models.IntegerField(),
        ),
    ]
