# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0014_auto_20161220_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionhasparameter',
            name='connectionParameter',
        ),
        migrations.RemoveField(
            model_name='connectionhasparameter',
            name='connectionType',
        ),
        migrations.RemoveField(
            model_name='connectiontype',
            name='parameters',
        ),
        migrations.AddField(
            model_name='connectionhasparameter',
            name='format',
            field=models.CharField(choices=[('int', 'Integer'), ('txt', 'Text'), ('bin', 'Binary'), ('Bit', 'Bits'), ('Byte', 'Byte'), ('IP', 'IP Address')], default='txt', max_length=10),
        ),
        migrations.AddField(
            model_name='connectionhasparameter',
            name='parameterName',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionhasparameter',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConnectionParameter',
        ),
    ]
