# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0015_auto_20161220_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontype',
            name='parameters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='connectiontypes.ConnectionHasParameter'),
            preserve_default=False,
        ),
    ]
