# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontypes', '0016_connectiontype_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontype',
            name='parameters',
        ),
        migrations.AddField(
            model_name='connectionhasparameter',
            name='connectiontype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='connectiontypes.ConnectionType'),
            preserve_default=False,
        ),
    ]
