# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20161123_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Number or Name'),
        ),
    ]
