# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20161123_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
